### ISSUE TITLE
WITX enums as language enums

### ISSUE THREAD

**Issue by radu-matei** [jedisct1/witx-codegen#5]
Currently, at least in Rust and AssemblyScript, WITX enums are represented as either modules or namespaces.
Is there a reason they wouldn't be an `enum`?
I realize guest implementation would not directly expose the generated code, just wondering why they would not directly be language enums.

(Also, this is great, thank you so much for this project!)

**Comment by jedisct1** [comment]
Hi!

The reason is that enums as exposed by WebAssembly ABI don't match at all the way Rust encodes them. 

An actual `enum` can be generated, but then we would need to copy data back and forth to match the WebAssembly representation. A pointer to a WebAssembly enum cannot be directly used as a pointer to a Rust enum. 

That being said, the generated AssemblyScript and Rust code will certainly be improved to do more automatic conversions.

Cheers!

(Have you tried the new markdown output? It's nice: https://github.com/jedisct1/witx-codegen/blob/master/example-output/markdown.md )
